version: '3.2'

services:

  openvpn:
    image: flavioaiello/openvpn:latest
    network_mode: "host"
    privileged: true
    volumes:
      - ${ROOT}/openvpn:/etc/openvpn
    env_file: .env
    environment:
      - CLIENTS=max hans peter
      - SERVICE_URL=openvpn.vcap.me
    restart: always

  swarm-router:
    image: flavioaiello/swarm-router:latest
    environment:
      - HTTP_PORTS=80
      - TLS_PORTS=443
      - HTTP_BACKENDS_PORT=portainer:9000 nexus:8081
    ports:
      - "80:80"
      - "443:443"
      - "1111:1111"
    networks:
      default:
      routing:
    restart: always

  portainer:
    image: portainer/portainer:latest
    depends_on: 
      - swarm-router
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth -H unix:///var/run/docker.sock
    networks:
      default:
        aliases:
          - portainer.${DOMAIN}
    restart: always

  portainer-customizer:
    image: flavioaiello/portainer-customizer:latest
    depends_on:
      - swarm-router
    restart: always

  jenkins:
    image: flavioaiello/jenkins-dsl:latest
    depends_on: 
      - swarm-router
    privileged: true
    env_file: .env
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Zurich
      - JENKINS_OPTS=''
      - JENKINS_EXECUTORS=7
      - JENKINS_BUILDSDIR=$${JENKINS_HOME}/builds/$${ITEM_FULL_NAME}
      - JENKINS_BOOTSTRAP_REPOSITORY=ssh://git@github.com:flavioaiello/continuous.git
      - JENKINS_BOOTSTRAP_REPOSITORY_BRANCH=develop
      - JENKINS_BASIC_CREDENTIALS=docker:admin:safSFDSgRJSFAJLO3534ADdsa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/jenkins/workspace:/var/jenkins_home/workspace
      - ${ROOT}/jenkins/builds:/var/jenkins_home/builds
    networks:
      default:
        aliases:
          - jenkins.${DOMAIN}
    restart: always

  nexus:
    image: flavioaiello/nexus3:latest
    depends_on: 
      - swarm-router
    env_file: .env
    environment:
      - DOCKER_REPOSITORIES=default:5000
      - NEXUS_DEFAULT_PASSWORD=admin123
      - NEXUS_PASSWORD=safSFDSgRJSFAJLO3534ADdsa
    ports:
      - "5000:5000"
    volumes:
      - ${ROOT}/nexus:/nexus-data
    networks:
      default:
        aliases:
          - nexus.${DOMAIN}
    restart: always

networks:
  default:
    driver: overlay
  routing:
    driver: overlay
    attachable: true
